[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
name = "hls4ml-garnet-lite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "seaborn>=0.13.2",
    "tensorflow==2.12.0",
    "QKeras @ git+https://github.com/google/qkeras.git@78ea90fc381fef23faa4db0e1d88bd1173c1c644"
]
[project.optional-dependencies]
dev = [
    "pre-commit>=4.5.0",
    "jinja2>=3.1.6",
    "pytest>=9.0.1",
]

[tool.ruff]
target-version = "py310"

line-length = 125
indent-width = 4
exclude = [ "hls4ml/" ]

format.quote-style = "single"
format.skip-magic-trailing-comma = false
format.docstring-code-line-length = 125
format.docstring-code-format = true
lint.select = [ "E", "F", "F401", "I", "W" ]
lint.ignore = [ "E741" ]
lint.per-file-ignores = { "__init__.py" = [ "F401" ] }

lint.fixable = [ "ALL" ]
lint.unfixable = [  ]

[tool.pytest.ini_options]
norecursedirs = [
    "hls4ml",
]
python_files = "test_*.py generate_test_vectors.py"

[tool.setuptools.packages.find]
where = ["."]
include = ["utils*", "hls4ml_garnet_lite*"]
exclude = ["tests*", "scripts*", "notebooks*", "data*", "hls4ml"]
namespaces = false

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
hls4ml-garnet-lite = { workspace = true, editable = true }

[dependency-groups]
dev = [
    "hls4ml-garnet-lite",
]
